"""Canonical core models for Onomasticon."""

from onomasticon.core.appellations import Appellation, AppellationKind
from onomasticon.core.documentary import (
    AnyDocumentaryUnit,
    Component,
    ContentItem,
    DocumentaryType,
    Holding,
    documentary_type_for_unit,
)
from onomasticon.core.entities import (
    AnyEntity,
    Entity,
    EntityType,
    Expression,
    Item,
    Manifestation,
    Organization,
    OrganizationSubtype,
    Person,
    Place,
    PlaceSubtype,
    Work,
)
from onomasticon.core.identifiers import Identifier
from onomasticon.core.local_ids import (
    LOCAL_IDENTIFIER_LENGTH,
    validate_local_identifier,
)
from onomasticon.core.properties import (
    StatementProperty,
    property_allowed_for_documentary_type,
    property_allowed_for_entity_type,
)
from onomasticon.core.reconciliation import (
    ExternalAuthorityTarget,
    LocalEntityTarget,
    Mention,
    ResolutionStatus,
    MentionTarget,
)
from onomasticon.core.ports import (
    DocumentaryCodec,
    DocumentaryStore,
    EntityCodec,
    EntityStore,
    SourceRecordCodec,
    SourceRecordStore,
)
from onomasticon.core.repository import EntityRepository, RepositoryLayout
from onomasticon.core.repository import (
    EntityValidationError,
    EntityWriteError,
    IdentifierCollisionError,
    RepositoryError,
)
from onomasticon.core.statements import (
    Ascription,
    AscriptionValue,
    Certainty,
    CoordinateValue,
    DateValue,
    EntityValue,
    IdentifierValue,
    LanguageTagValue,
    Qualifier,
    QualifierProperty,
    Reference,
    Sex,
    SexValue,
    Statement,
    StatementStatus,
    StatementValue,
    TextValue,
)
from onomasticon.core.temporal import TemporalValue

__all__ = [
    "Appellation",
    "AppellationKind",
    "AnyEntity",
    "AnyDocumentaryUnit",
    "Ascription",
    "AscriptionValue",
    "Certainty",
    "Component",
    "ContentItem",
    "CoordinateValue",
    "DateValue",
    "DocumentaryType",
    "DocumentaryCodec",
    "DocumentaryStore",
    "Entity",
    "EntityCodec",
    "EntityRepository",
    "EntityStore",
    "EntityValue",
    "EntityValidationError",
    "EntityWriteError",
    "EntityType",
    "Expression",
    "IdentifierValue",
    "Identifier",
    "IdentifierCollisionError",
    "Item",
    "LanguageTagValue",
    "LOCAL_IDENTIFIER_LENGTH",
    "Holding",
    "Manifestation",
    "Mention",
    "MentionTarget",
    "Organization",
    "OrganizationSubtype",
    "Person",
    "Place",
    "PlaceSubtype",
    "Qualifier",
    "QualifierProperty",
    "Reference",
    "RepositoryError",
    "RepositoryLayout",
    "ResolutionStatus",
    "Sex",
    "SexValue",
    "SourceRecordCodec",
    "SourceRecordStore",
    "Statement",
    "StatementProperty",
    "StatementStatus",
    "StatementValue",
    "TemporalValue",
    "TextValue",
    "Work",
    "documentary_type_for_unit",
    "ExternalAuthorityTarget",
    "LocalEntityTarget",
    "property_allowed_for_documentary_type",
    "property_allowed_for_entity_type",
    "validate_local_identifier",
]
